# 2 available formats for conditions_path file
# format 1: tab separated
# label  condition   replicate
# NCY38 CR      1
# NCY54 CR      2
# NCY70 CR      3
# NCY200        CR      4
# AVI01 R       1
# CLM01 R       2
# CLM07 R       3
#
# format 2: tab separated
# label condition       replicate       new_name
# NCY38 CR      1       newname_1
# NCY54 CR      2       newname_2
# NCY70 CR      3       newname_3
# AVI01 R       1       newname_4
# CLM01 R       2       newname_5
# CLM07 R       3       newname_6
seed: 123
conditions_path : "data/conditions_toy.txt"


# 2 available formats group thresholds: "file" (look for thresholds in a file) or "by_group" (use group_threshold on groups)
# "simple" (use global_threshold on all samples)
# "simple+group" (use group_threshold on at least 1 groups and global_threshold on all samples)
# 
group_threshold_mode : "simple+group"
# format for thresholds_path file
# tab separated
# R   CR   CS   S
# 16  7 15  5
thresholds_path : "data/thresholds.txt"
group_threshold : 0.6667
global_threshold: 0.5
MNAR_filter: TRUE
MNAR_threshold : "1/3"
atLeastOne : FALSE

partial_imputation: TRUE
partial_imputation_threshold: 0.3334

# protein id should be: Protein.IDs column
# hgnc should be: HGNC.symbol_result column
# prot_rename_db_path : "data/FIXED_ProteinDB_annots4127.txt"
prot_rename_db_path : "data/simple_rename_db.txt"

# proteinGroups_path and peptides_path are files from Max Quant
proteinGroups_path : "proteinGroups.txt"
peptides_path : "peptides.txt"

# "prot" to construct proteome, "pep" to construct peptidome, "both" to construct both
pipeline_mode: "prot"

# dependancy scripts
# max_quant_process_path: "max_quant_process.r"
# prot_filter_path: "prot_filter.r"
# prot_normalize_path: "prot_normalize.r"
# prot_impute_path: "prot_impute.r"
# rf_impute_lib_path : "rf_impute.r"
# prot_plots_path: "prot_plots.r"

# output directories
output_dir_new_names: "01_new_names"
output_dir_filtered: "02_filtered"
output_dir_normalized: "03_normalized"
output_dir_imputed: "04_imputed"
output_dir_prot_rename: "05_prot_rename"
output_dir_plots: "plots"

# output files
conditions_new_sample_names: "conditions_new_sample_names.txt"
prot_annotations_path: "prot_annotations.txt"
pep_annotations_path: "pep_annotations.txt"
output_proteome_data: "proteome_data.txt"
output_peptidome_data: "peptidome_data.txt"
output_both_data: "prot_pep_data.txt"

# Filter options
# filter : TRUE

remove_reverse_identified_contaminant: TRUE
peptide_occurence_filter: 2

# look at other algo in DEP
# Normalisation methods: "none", "vsn", "quantiles"
norm_method: "quantiles"


# Imputation_method methods: "rf", "knn", "none"
imputation_method: "rf"

# knn.impute parameters for "knn" imputation method
# knn_k: 10
# knn_rowmax: 0.4
# knn_colmax: 0.8
knn_k: 10
knn_rowmax: 0.4
knn_colmax: 0.8

# knn.impute parameters for "rf" imputation method
# rf_knn_k: 10
# rf_knn_rowmax: 0.4
# rf_knn_colmax: 0.8
rf_knn_k: 10
rf_knn_rowmax: 0.4
rf_knn_colmax: 0.8

# rename methods can be "file", "biomart", or "none"
rename_method: "biomart"
